# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/ktamamu/sglobal
  govet:
    shadow: true
  revive:
    severity: warning
    rules:
      - name: exported
        disabled: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - gocritic
    - gosec
    - revive
    - misspell
    - unconvert
    - unparam

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0